import { NextResponse } from "next/server";
import { and, eq, gt } from "drizzle-orm";
import { getDb } from "@/db";
import { userAccounts,userSessions } from "@/db/schema";
import { createSessionToken,hashPassword,hashSessionToken,verifyPassword } from "@/lib/account-auth";

const COOKIE="mim_session";
function validOrigin(request:Request){const origin=request.headers.get("origin");return !origin||new URL(origin).host===new URL(request.url).host;}
export async function GET(request:Request){const token=request.headers.get("cookie")?.match(/(?:^|; )mim_session=([^;]+)/)?.[1];if(!token)return NextResponse.json({user:null});const [row]=await getDb().select({email:userAccounts.email,role:userAccounts.role}).from(userSessions).innerJoin(userAccounts,eq(userAccounts.id,userSessions.userId)).where(and(eq(userSessions.tokenHash,hashSessionToken(decodeURIComponent(token))),gt(userSessions.expiresAt,new Date()))).limit(1);return NextResponse.json({user:row??null});}
export async function POST(request:Request){if(!validOrigin(request))return NextResponse.json({error:"Invalid origin"},{status:403});const body=await request.json().catch(()=>null) as {action?:string;email?:string;password?:string}|null;const action=body?.action;const email=String(body?.email??"").trim().toLowerCase().slice(0,254);const password=String(body?.password??"");const db=getDb();if(action==="logout"){const token=request.headers.get("cookie")?.match(/(?:^|; )mim_session=([^;]+)/)?.[1];if(token)await db.delete(userSessions).where(eq(userSessions.tokenHash,hashSessionToken(decodeURIComponent(token))));const response=NextResponse.json({ok:true});response.cookies.set(COOKIE,"",{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"strict",path:"/",maxAge:0});return response;}if(!/^\S+@\S+\.\S+$/.test(email)||password.length<10||password.length>128)return NextResponse.json({error:"Use a valid email and a password with at least 10 characters."},{status:400});let user;if(action==="signup"){const passwordHash=await hashPassword(password);try{[user]=await db.insert(userAccounts).values({email,passwordHash}).returning({id:userAccounts.id,email:userAccounts.email,role:userAccounts.role});}catch{return NextResponse.json({error:"This email already has an account."},{status:409});}}else if(action==="login"){const [stored]=await db.select().from(userAccounts).where(eq(userAccounts.email,email)).limit(1);if(!stored||!(await verifyPassword(password,stored.passwordHash)))return NextResponse.json({error:"Invalid email or password."},{status:401});user={id:stored.id,email:stored.email,role:stored.role};}else return NextResponse.json({error:"Invalid action"},{status:400});const token=createSessionToken();const expiresAt=new Date(Date.now()+30*24*60*60*1000);await db.insert(userSessions).values({tokenHash:hashSessionToken(token),userId:user.id,expiresAt});const response=NextResponse.json({user:{email:user.email,role:user.role}});response.cookies.set(COOKIE,token,{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"strict",path:"/",expires:expiresAt});return response;}
