export const LOCALES = ["en", "pt", "es", "de", "fr"] as const;
export type Locale = typeof LOCALES[number];

export const UI_STRINGS: Record<Locale, Record<string, string>> = {
  en:{announcement:"Made in Maia · Free shipping in Portugal from €45",new:"New",choose:"Choose options",search:"Search designs",bag:"Your bag",emptyBag:"You haven't added a design yet.",checkout:"Continue to checkout",secureCheckout:"Secure checkout with Viva.com or Stripe.",collections:"Collections",brand:"The brand",discover:"Discover",where:"Find us",kids:"Kids",adults:"Adults",size:"Size",colour:"Colour",support:"Product",add:"Add to bag",menu:"Open menu",explore:"Explore",viewBag:"View shopping bag",remove:"Remove",noDesigns:"No designs found.",loading:"Loading…",loadMore:"Load more",previous:"Previous",next:"Next",page:"Page",terms:"Terms",privacy:"Privacy",returns:"Exchanges and returns",designOnly:"Design only",garmentColours:"Product colours",printColour:"Print colour",blackPrint:"Black print",whitePrint:"White print"},
  pt:{announcement:"Produzido na Maia · Envio gratuito em Portugal a partir de 45 €",new:"Novo",choose:"Escolher opções",search:"Pesquisar designs",bag:"O teu saco",emptyBag:"Ainda não adicionaste nenhum design.",checkout:"Continuar para pagamento",secureCheckout:"Checkout seguro por Viva.com ou Stripe.",collections:"Coleções",brand:"A marca",discover:"Descobre",where:"Onde estamos",kids:"Criança",adults:"Adulto",size:"Tamanho",colour:"Cor",support:"Produto",add:"Adicionar ao saco",menu:"Abrir menu",explore:"Explorar",viewBag:"Ver saco de compras",remove:"Remover",noDesigns:"Nenhum design encontrado.",loading:"A carregar…",loadMore:"Carregar mais",previous:"Anterior",next:"Seguinte",page:"Página",terms:"Termos",privacy:"Privacidade",returns:"Trocas e devoluções",designOnly:"Apenas design",garmentColours:"Cores do produto",printColour:"Cor de impressão",blackPrint:"Impressão preta",whitePrint:"Impressão branca"},
  es:{announcement:"Hecho en Maia · Envío gratuito en Portugal desde 45 €",new:"Nuevo",choose:"Elegir opciones",search:"Buscar diseños",bag:"Tu bolsa",emptyBag:"Todavía no has añadido ningún diseño.",checkout:"Continuar al pago",secureCheckout:"Pago seguro con Viva.com o Stripe.",collections:"Colecciones",brand:"La marca",discover:"Descubre",where:"Dónde estamos",kids:"Niños",adults:"Adultos",size:"Talla",colour:"Color",support:"Producto",add:"Añadir a la bolsa",menu:"Abrir menú",explore:"Explorar",viewBag:"Ver bolsa",remove:"Eliminar",noDesigns:"No se encontraron diseños.",loading:"Cargando…",loadMore:"Cargar más",previous:"Anterior",next:"Siguiente",page:"Página",terms:"Términos",privacy:"Privacidad",returns:"Cambios y devoluciones",designOnly:"Solo diseño",garmentColours:"Colores del producto",printColour:"Color de impresión",blackPrint:"Impresión negra",whitePrint:"Impresión blanca"},
  de:{announcement:"Made in Maia · Kostenloser Versand in Portugal ab 45 €",new:"Neu",choose:"Optionen wählen",search:"Designs suchen",bag:"Deine Tasche",emptyBag:"Du hast noch kein Design hinzugefügt.",checkout:"Zur Kasse",secureCheckout:"Sicherer Checkout mit Viva.com oder Stripe.",collections:"Kollektionen",brand:"Die Marke",discover:"Entdecken",where:"Wo wir sind",kids:"Kinder",adults:"Erwachsene",size:"Größe",colour:"Farbe",support:"Produkt",add:"In den Warenkorb",menu:"Menü öffnen",explore:"Entdecken",viewBag:"Warenkorb anzeigen",remove:"Entfernen",noDesigns:"Keine Designs gefunden.",loading:"Wird geladen…",loadMore:"Mehr laden",previous:"Zurück",next:"Weiter",page:"Seite",terms:"Bedingungen",privacy:"Datenschutz",returns:"Umtausch und Rückgabe",designOnly:"Nur Design",garmentColours:"Produktfarben",printColour:"Druckfarbe",blackPrint:"Schwarzer Druck",whitePrint:"Weißer Druck"},
  fr:{announcement:"Fabriqué à Maia · Livraison gratuite au Portugal dès 45 €",new:"Nouveau",choose:"Choisir les options",search:"Rechercher des designs",bag:"Votre sac",emptyBag:"Vous n’avez encore ajouté aucun design.",checkout:"Passer au paiement",secureCheckout:"Paiement sécurisé avec Viva.com ou Stripe.",collections:"Collections",brand:"La marque",discover:"Découvrir",where:"Où nous trouver",kids:"Enfants",adults:"Adultes",size:"Taille",colour:"Couleur",support:"Produit",add:"Ajouter au sac",menu:"Ouvrir le menu",explore:"Explorer",viewBag:"Voir le panier",remove:"Supprimer",noDesigns:"Aucun design trouvé.",loading:"Chargement…",loadMore:"Charger plus",previous:"Précédent",next:"Suivant",page:"Page",terms:"Conditions",privacy:"Confidentialité",returns:"Échanges et retours",designOnly:"Design seul",garmentColours:"Couleurs du produit",printColour:"Couleur d’impression",blackPrint:"Impression noire",whitePrint:"Impression blanche"},
};

const NAV_LABELS: Record<string, Partial<Record<Locale,string>>> = {
  new:{pt:"Novidades",es:"Novedades",de:"Neu",fr:"Nouveautés"},
  collections:{pt:"Coleções",es:"Colecciones",de:"Kollektionen",fr:"Collections"},
  discover:{pt:"Descobre",es:"Descubre",de:"Entdecken",fr:"Découvrir"},
  brand:{pt:"A marca",es:"La marca",de:"Die Marke",fr:"La marque"},
};

export function translatedNavigation(id:string, label:string, locale:Locale) {
  return locale === "en" ? label : NAV_LABELS[id]?.[locale] ?? label;
}

export function translatedName(name:string, translations:Record<string,string>|undefined, locale:Locale) {
  return locale === "en" ? name : translations?.[locale]?.trim() || name;
}
