"use client";

import Link from "next/link";
import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
import { ArrowRight,Box,ExternalLink,LoaderCircle,LogOut,Search } from "lucide-react";
import { BrandLogo } from "@/components/brand-logo";

type User={email:string;role:string};
type Order={reference:string;status:string;items:Array<{name:string;productType:string;color:string;size:string;quantity:number;unitPriceCents:number}>;shippingCents:number;totalCents:number;trackingCode:string;trackingUrl:string;createdAt:string};
type AccountPayload={user:User|null;orders:Order[];error?:string};
const labels:Record<string,string>={pending:"Received",paid:"Paid",preparing:"Preparing",shipped:"Shipped",completed:"Completed",cancelled:"Cancelled",refunded:"Refunded"};
const money=(value:number)=>new Intl.NumberFormat("en-IE",{style:"currency",currency:"EUR"}).format(value/100);

export default function AccountPage(){
  const [user,setUser]=useState<User|null>(null);
  const [orders,setOrders]=useState<Order[]>([]);
  const [loading,setLoading]=useState(true);
  const [mode,setMode]=useState<"login"|"signup">("login");
  const [message,setMessage]=useState("");
  const [query,setQuery]=useState("");
  const [status,setStatus]=useState("all");
  const loadAccount=useCallback(async()=>{try{const response=await fetch("/api/account",{cache:"no-store"});const data=await response.json() as AccountPayload;if(!response.ok)throw new Error(data.error);setUser(data.user);setOrders(data.orders??[]);}catch{setMessage("Could not load your account.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void fetch("/api/account",{cache:"no-store"}).then((response)=>response.json() as Promise<AccountPayload>).then((data)=>{setUser(data.user);setOrders(data.orders??[]);}).catch(()=>setMessage("Could not load your account.")).finally(()=>setLoading(false));},[]);
  const filtered=useMemo(()=>orders.filter((order)=>{const haystack=[order.reference,...order.items.map((item)=>item.name)].join(" ").toLowerCase();return (status==="all"||order.status===status)&&haystack.includes(query.trim().toLowerCase());}),[orders,query,status]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setMessage("");const form=new FormData(event.currentTarget);const response=await fetch("/api/account",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:mode,email:form.get("email"),password:form.get("password")})});const data=await response.json() as {error?:string};if(!response.ok)return setMessage(data.error??"Could not sign in.");setLoading(true);await loadAccount();}
  async function logout(){await fetch("/api/account",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"logout"})});setUser(null);setOrders([]);}
  async function deleteAccount(){if(!window.confirm("Delete this account permanently? Your order records will be retained for legal and accounting purposes."))return;const response=await fetch("/api/account",{method:"DELETE"});if(!response.ok){setMessage("Could not delete your account.");return;}setUser(null);setOrders([]);}
  return <main className="storefront-dark min-h-screen bg-[var(--paper)] text-white">
    <header className="flex items-center justify-between border-b border-white/10 px-4 py-3 sm:px-8"><Link href="/loja"><BrandLogo className="h-14 w-auto"/></Link><Link href="/loja" className="inline-flex items-center gap-2 text-xs font-black uppercase">Shop<ArrowRight className="size-4"/></Link></header>
    {loading?<div className="grid min-h-[60vh] place-items-center"><LoaderCircle className="size-8 animate-spin text-[var(--brand)]"/></div>:user?
      <section className="mx-auto max-w-6xl px-4 py-10 sm:px-6 sm:py-16">
        <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[var(--brand)]">Made in Maia</p><h1 className="mt-2 text-5xl font-black uppercase tracking-[-.06em] sm:text-7xl">My orders</h1><p className="mt-3 text-white/50">{user.email}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>void deleteAccount()} className="h-11 border border-red-500/40 px-4 text-xs font-black uppercase text-red-300 hover:bg-red-500 hover:text-white">Delete account</button><button onClick={()=>void logout()} className="inline-flex h-11 items-center gap-2 border border-white/20 px-4 text-xs font-black uppercase hover:bg-white hover:text-black"><LogOut className="size-4"/>Sign out</button></div></div>
        <div className="mt-10 grid gap-3 border-y border-white/10 py-4 md:grid-cols-[minmax(0,1fr)_220px]"><label className="flex items-center gap-3 border border-white/15 bg-white/5 px-4"><Search className="size-4 text-white/45"/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search order or design" className="h-12 min-w-0 flex-1 bg-transparent outline-none placeholder:text-white/35"/></label><select value={status} onChange={(event)=>setStatus(event.target.value)} className="h-12 border border-white/15 bg-[#171716] px-4 font-bold"><option value="all">All statuses</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>
        <div className="mt-6 space-y-3">{filtered.map((order)=><details key={order.reference} className="group border border-white/15 bg-white/[.035]"><summary className="grid cursor-pointer list-none gap-3 p-4 sm:grid-cols-[minmax(0,1fr)_auto_auto] sm:items-center sm:p-5 [&::-webkit-details-marker]:hidden"><div className="min-w-0"><p className="font-mono text-sm font-black text-[var(--brand)]">{order.reference}</p><p className="mt-1 text-xs text-white/45">{new Date(order.createdAt).toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"})} · {order.items.reduce((sum,item)=>sum+item.quantity,0)} item(s)</p></div><span className="w-fit rounded-full border border-white/15 px-3 py-1.5 text-[10px] font-black uppercase">{labels[order.status]??order.status}</span><strong className="text-xl">{money(order.totalCents)}</strong></summary><div className="border-t border-white/10 p-4 sm:p-5"><ul className="space-y-3">{order.items.map((item,index)=><li key={index} className="grid grid-cols-[minmax(0,1fr)_auto] gap-4 text-sm"><span>{item.quantity}× <strong>{item.name}</strong><span className="block text-xs text-white/45">{item.productType} · {item.size} · {item.color}</span></span><strong>{money(item.unitPriceCents*item.quantity)}</strong></li>)}</ul><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-4"><p className="text-sm text-white/55">Shipping: <strong className="text-white">{order.shippingCents?money(order.shippingCents):"Free"}</strong></p>{order.trackingUrl?<a href={order.trackingUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 bg-[var(--brand)] px-4 py-3 text-xs font-black uppercase text-white">Track shipment<ExternalLink className="size-4"/></a>:order.trackingCode?<p className="font-mono text-sm"><span className="mr-2 text-white/45">Tracking</span>{order.trackingCode}</p>:<p className="inline-flex items-center gap-2 text-xs font-bold uppercase text-white/40"><Box className="size-4"/>Tracking appears after dispatch</p>}</div></div></details>)}{!filtered.length&&<div className="grid min-h-56 place-items-center border border-dashed border-white/15 text-center"><div><Box className="mx-auto size-8 text-white/25"/><p className="mt-3 font-black uppercase">{orders.length?"No matching orders":"No orders yet"}</p><p className="mt-1 text-sm text-white/45">{orders.length?"Try another search or status.":"Orders using this email will appear here."}</p></div></div>}</div>
      </section>:
      <section className="mx-auto max-w-md px-5 py-16"><p className="text-xs font-black uppercase tracking-[.2em] text-[var(--brand)]">Made in Maia</p><h1 className="mt-2 text-5xl font-black uppercase">Account</h1><p className="mt-4 text-white/50">Sign in to follow orders placed with the same email address.</p><div className="mt-7 grid grid-cols-2 border border-white/15 p-1"><button onClick={()=>setMode("login")} className={`py-3 font-black uppercase ${mode==="login"?"bg-white text-black":""}`}>Sign in</button><button onClick={()=>setMode("signup")} className={`py-3 font-black uppercase ${mode==="signup"?"bg-white text-black":""}`}>Create account</button></div><form onSubmit={submit} className="mt-5 grid gap-4"><label className="grid gap-1 text-xs font-black uppercase">Email<input required name="email" type="email" autoComplete="email" className="h-12 border border-white/15 bg-white/5 px-4 text-base normal-case"/></label><label className="grid gap-1 text-xs font-black uppercase">Password<input required minLength={10} name="password" type="password" autoComplete={mode==="login"?"current-password":"new-password"} className="h-12 border border-white/15 bg-white/5 px-4 text-base normal-case"/></label>{message&&<p className="text-sm text-red-400">{message}</p>}<button className="h-13 bg-[var(--brand)] font-black uppercase">{mode==="login"?"Sign in":"Create account"}</button></form></section>}
  </main>;
}
