"use client";
import Link from "next/link";
import { FormEvent,useEffect,useState } from "react";
import { BrandLogo } from "@/components/brand-logo";
type User={email:string;role:string};
export default function AccountPage(){
  const [user,setUser]=useState<User|null>(null);const [mode,setMode]=useState<"login"|"signup">("login");const [message,setMessage]=useState("");
  useEffect(()=>{void fetch("/api/account").then((response)=>response.json() as Promise<{user:User|null}>).then((data)=>setUser(data.user));},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch("/api/account",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:mode,email:form.get("email"),password:form.get("password")})});const data=await response.json() as {error?:string;user?:User};if(!response.ok)return setMessage(data.error??"Could not sign in.");setUser(data.user??null);setMessage("");}
  async function logout(){await fetch("/api/account",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"logout"})});setUser(null);}
  return <main className="storefront-dark min-h-screen bg-[var(--paper)] text-white"><header className="flex items-center justify-between border-b border-white/10 px-4 py-3"><Link href="/loja"><BrandLogo className="h-14 w-auto"/></Link><Link href="/loja" className="text-xs font-black uppercase">Shop</Link></header><section className="mx-auto max-w-md px-5 py-16"><p className="text-xs font-black uppercase tracking-[.2em] text-[var(--brand)]">Made in Maia</p><h1 className="mt-2 text-5xl font-black uppercase">Account</h1>{user?<div className="mt-8 border border-white/15 bg-white/5 p-6"><p className="text-sm text-white/55">Signed in as</p><strong className="mt-1 block text-xl">{user.email}</strong><p className="mt-1 text-xs uppercase text-white/40">{user.role}</p><button onClick={()=>void logout()} className="mt-8 h-12 w-full border border-white/20 font-black uppercase">Sign out</button></div>:<><div className="mt-7 grid grid-cols-2 border border-white/15 p-1"><button onClick={()=>setMode("login")} className={`py-3 font-black uppercase ${mode==="login"?"bg-white text-black":""}`}>Sign in</button><button onClick={()=>setMode("signup")} className={`py-3 font-black uppercase ${mode==="signup"?"bg-white text-black":""}`}>Create account</button></div><form onSubmit={submit} className="mt-5 grid gap-4"><label className="grid gap-1 text-xs font-black uppercase">Email<input required name="email" type="email" autoComplete="email" className="h-12 border border-white/15 bg-white/5 px-4 text-base normal-case"/></label><label className="grid gap-1 text-xs font-black uppercase">Password<input required minLength={10} name="password" type="password" autoComplete={mode==="login"?"current-password":"new-password"} className="h-12 border border-white/15 bg-white/5 px-4 text-base normal-case"/></label>{message&&<p className="text-sm text-red-400">{message}</p>}<button className="h-13 bg-[var(--brand)] font-black uppercase">{mode==="login"?"Sign in":"Create account"}</button></form></>}</section></main>;
}
